const FAV_KEY='ssfamily-favorites';let favorites=new Set(JSON.parse(localStorage.getItem(FAV_KEY)||'[]'));let stocks=[],financials={stocks:{}};let currentView='rank',favOnly=false;
const reportLabel=f=>f?`${f.businessYear} ${f.reportName}`:'DART 갱신 전';
async function init(){[stocks,financials]=await Promise.all([fetch('data/stocks.json').then(r=>r.json()),fetch('data/financials.json').then(r=>r.json())]);updateFavCount();renderStats();renderRank()}
function updateFavCount(){document.getElementById('favCount').textContent=favorites.size}
function visible(){return stocks.filter(s=>!favOnly||favorites.has(s.code))}
function renderStats(){const loaded=stocks.filter(s=>financials.stocks?.[s.code]).length;const industries=new Set(stocks.map(s=>s.industry));document.getElementById('statGrid').innerHTML=`<div class="stat-card"><div class="stat-label">대상 기업</div><div class="stat-value">${stocks.length}<span class="stat-unit"> 개</span></div></div><div class="stat-card"><div class="stat-label">해당 업종</div><div class="stat-value">${industries.size}<span class="stat-unit"> 개</span></div></div><div class="stat-card"><div class="stat-label">DART 연동</div><div class="stat-value">${loaded}<span class="stat-unit"> / ${stocks.length}</span></div></div><div class="stat-card"><div class="stat-label">재무정보 기준</div><div class="stat-value">${financials.businessYear||'—'}<span class="stat-unit"> 년</span></div></div>`}
function starButton(s){const b=document.createElement('button');b.className='star-btn'+(favorites.has(s.code)?' active':'');b.type='button';b.textContent=favorites.has(s.code)?'★':'☆';b.setAttribute('aria-label','즐겨찾기');b.onclick=e=>{e.stopPropagation();favorites.has(s.code)?favorites.delete(s.code):favorites.add(s.code);localStorage.setItem(FAV_KEY,JSON.stringify([...favorites]));updateFavCount();rerender()};return b}
function go(s){location.href=`stock.html?code=${s.code}`}
function renderRank(){currentView='rank';document.getElementById('mainTitle').textContent='SS Family 관심기업 - 순위별 보기';const area=document.getElementById('stockArea');const list=visible();if(!list.length){area.innerHTML='<div class="empty-view">즐겨찾기한 기업이 없습니다.</div>';return}const table=document.createElement('div');table.className='rank-table';table.innerHTML='<div class="rank-table-head"><div>순위</div><div>기업명</div><div>업종</div><div>최근 재무정보</div><div></div></div>';list.sort((a,b)=>a.rank-b.rank).forEach(s=>{const f=financials.stocks?.[s.code];const row=document.createElement('div');row.className='rank-row';row.innerHTML=`<div class="rank-num">${String(s.rank).padStart(2,'0')}</div><div><div class="stock-name">${s.name}</div><div class="stock-code">${s.code}</div></div><div class="industry">${s.industry}</div><div class="report-state">${reportLabel(f)}</div>`;row.appendChild(starButton(s));row.onclick=()=>go(s);table.appendChild(row)});area.replaceChildren(table)}
function renderIndustry(){currentView='industry';document.getElementById('mainTitle').textContent='SS Family 관심기업 - 업종별 보기';const area=document.getElementById('stockArea');area.innerHTML='';const list=visible();if(!list.length){area.innerHTML='<div class="empty-view">즐겨찾기한 기업이 없습니다.</div>';return}[...new Set(list.map(s=>s.industry))].forEach(ind=>{const members=list.filter(s=>s.industry===ind).sort((a,b)=>a.rank-b.rank);const sec=document.createElement('section');sec.className='industry-section';sec.innerHTML=`<div class="industry-header"><h3 class="industry-title">${ind}</h3><span class="industry-count">${members.length}개 기업</span></div>`;members.forEach(s=>{const row=document.createElement('div');row.className='sector-row';const left=document.createElement('div');left.className='sr-left';left.appendChild(starButton(s));const info=document.createElement('div');info.innerHTML=`<div class="stock-name">${s.name}</div><div class="stock-code">${s.code}</div>`;left.appendChild(info);row.appendChild(left);const rep=document.createElement('div');rep.className='sr-report';rep.textContent=reportLabel(financials.stocks?.[s.code]);row.appendChild(rep);row.onclick=()=>go(s);sec.appendChild(row)});area.appendChild(sec)})}
function rerender(){currentView==='rank'?renderRank():renderIndustry()}
document.getElementById('rankViewBtn').onclick=()=>{document.getElementById('rankViewBtn').classList.add('active');document.getElementById('industryViewBtn').classList.remove('active');renderRank()};document.getElementById('industryViewBtn').onclick=()=>{document.getElementById('industryViewBtn').classList.add('active');document.getElementById('rankViewBtn').classList.remove('active');renderIndustry()};document.getElementById('favOnlyCheckbox').onchange=e=>{favOnly=e.target.checked;rerender()};
init().catch(e=>{document.getElementById('stockArea').innerHTML=`<div class="empty-view">데이터를 불러오지 못했습니다.<br>${e.message}</div>`});
