const code=new URLSearchParams(location.search).get('code');const SECTIONS=['tech','fund','valuation','timeline','thesis','consensus'];
const A={assets:['자산총계'],liabilities:['부채총계'],equity:['자본총계'],revenue:['매출액','영업수익','수익(매출액)','이자수익'],operating:['영업이익','영업이익(손실)','영업손익'],net:['당기순이익','당기순이익(손실)','연결당기순이익','분기순이익'],cash:['현금및현금성자산','현금및현금성자산의순증가(감소)'],eps:['기본주당이익','기본주당순이익']};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function pick(rows,names){return rows.find(r=>names.includes(r.accountName))||rows.find(r=>names.some(n=>r.accountName?.includes(n)))}
function money(v){if(v===null||v===undefined)return '—';const n=Number(v),a=Math.abs(n),sign=n<0?'-':'';if(a>=1e12)return `${sign}${(a/1e12).toFixed(1)}조원`;if(a>=1e8)return `${sign}${(a/1e8).toFixed(0)}억원`;return `${n.toLocaleString('ko-KR')}원`}
function pct(v,d=1){return Number.isFinite(v)?`${v>=0?'+':''}${v.toFixed(d)}%`:'—'}
function change(r){if(!r||!r.previousAmount)return null;return (r.currentAmount-r.previousAmount)/Math.abs(r.previousAmount)*100}
function row(label,r){const c=change(r);return `<div class="dp-row2"><span class="l">${esc(label)}</span><span class="v ${c===null?'':c>=0?'up':'dn'}">${money(r?.currentAmount)}${c===null?'':` (${pct(c)})`}</span></div>`}
function fullTable(rows){if(!rows.length)return '<div class="dp-placeholder">해당 재무제표 항목이 없습니다.</div>';return `<div class="financial-scroll"><table class="financial-table"><thead><tr><th>계정</th><th>당기</th><th>전기</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.accountName)}</td><td>${money(r.currentAmount)}</td><td>${money(r.previousAmount)}</td></tr>`).join('')}</tbody></table></div>`}
function gauge(label,value,note,width){return `<div class="dp-gauge"><div class="dp-gauge-h"><span>${label}</span><span>${value}</span></div><div class="dp-gauge-track"><div class="dp-gauge-fill" style="width:${Math.max(3,Math.min(100,width))}%"></div></div><div class="dp-gauge-note">${note}</div></div>`}
function renderConsensus(c){if(!c||c.status!=='available')return `<div class="dp-placeholder"><strong>${esc(c?.label||'컨센서스 없음')}</strong><br>${esc(c?.note||'확인 가능한 최근 증권사 컨센서스가 없습니다.')}<br>${c?.asOf?`확인일 ${esc(c.asOf)}`:''}</div>`;const upside=c.closePrice?((c.targetPrice/c.closePrice-1)*100):NaN;return `<div class="dp-share4"><div class="dp-share"><div class="dp-share-l">투자의견</div><div class="dp-share-v">${esc(c.rating)}</div><div class="dp-share-s">수동 스냅샷</div></div><div class="dp-share"><div class="dp-share-l">평균 목표주가</div><div class="dp-share-v">${Number(c.targetPrice).toLocaleString('ko-KR')}원</div><div class="dp-share-s">${esc(c.asOf)} 기준</div></div><div class="dp-share"><div class="dp-share-l">기준 종가</div><div class="dp-share-v">${Number(c.closePrice).toLocaleString('ko-KR')}원</div><div class="dp-share-s">${esc(c.asOf)} 기준</div></div><div class="dp-share"><div class="dp-share-l">목표가 괴리</div><div class="dp-share-v">${pct(upside)}</div><div class="dp-share-s">목표가 ÷ 종가</div></div></div><div class="dp-insight"><div class="dp-insight-t">출처 및 갱신 안내</div><div class="dp-insight-b">${esc(c.sourceName)}에서 ${esc(c.capturedAt)}에 직접 확인한 스냅샷입니다. 자동 갱신되지 않으며 현재 값과 다를 수 있습니다. <a href="${esc(c.sourceUrl)}" target="_blank" rel="noopener noreferrer">원문 확인</a></div></div>`}
function dpToggle(id){document.getElementById('dpAcc-'+id)?.classList.toggle('open')}function dpOpenAll(){SECTIONS.forEach(id=>document.getElementById('dpAcc-'+id)?.classList.add('open'))}function dpCloseAll(){SECTIONS.forEach(id=>document.getElementById('dpAcc-'+id)?.classList.remove('open'))}window.dpToggle=dpToggle;window.dpOpenAll=dpOpenAll;window.dpCloseAll=dpCloseAll;
function render(stock,f,data){const rows=f.accounts||[],assets=pick(rows,A.assets),liab=pick(rows,A.liabilities),equity=pick(rows,A.equity),rev=pick(rows,A.revenue),op=pick(rows,A.operating),net=pick(rows,A.net),cash=pick(rows,A.cash),eps=pick(rows,A.eps);const av=Number(assets?.currentAmount),lv=Number(liab?.currentAmount),ev=Number(equity?.currentAmount),rv=Number(rev?.currentAmount),ov=Number(op?.currentAmount),nv=Number(net?.currentAmount);const debt=av?lv/av*100:NaN,equityRatio=av?ev/av*100:NaN,opMargin=rv?ov/rv*100:NaN,netMargin=rv?nv/rv*100:NaN;const report=`${f.businessYear}년 ${f.reportName}`;const fs=f.fsDivision==='CFS'?'연결':'별도';const summary=`${stock.name}의 ${report} ${fs}재무제표 기준 자산은 ${money(assets?.currentAmount)}, 자본은 ${money(equity?.currentAmount)}입니다. ${rev?`매출·영업수익은 ${money(rev.currentAmount)}`:'매출·영업수익 계정은 업종별 표시 기준을 확인해야 합니다'}${op?`, 영업이익은 ${money(op.currentAmount)}`:''}${net?`, 당기순이익은 ${money(net.currentAmount)}`:''}. 아래 수치는 OpenDART 원문에서 자동 구성했습니다.`;
document.getElementById('detailRoot').innerHTML=`
<div class="dp-title-row"><h1 class="dp-h1">${esc(stock.name)}</h1><span class="dp-ticker">${stock.code}</span><span class="dp-badge">코스피 · ${esc(stock.industry)}</span></div>
<div class="dp-price-row"><div class="dp-price">${report}</div><div class="dp-chg">OpenDART</div><div class="dp-date">${esc(data.generatedAt?.slice(0,10)||'갱신일 미상')} 데이터 갱신</div></div>
<div class="dp-stats"><div class="dp-stat"><div class="dp-stat-l">자산총계</div><div class="dp-stat-v">${money(assets?.currentAmount)}</div></div><div class="dp-stat"><div class="dp-stat-l">자본총계</div><div class="dp-stat-v">${money(equity?.currentAmount)}</div></div><div class="dp-stat"><div class="dp-stat-l">매출·영업수익</div><div class="dp-stat-v">${money(rev?.currentAmount)}</div></div><div class="dp-stat"><div class="dp-stat-l">당기순이익</div><div class="dp-stat-v">${money(net?.currentAmount)}</div></div></div>
<div class="dp-summary"><div class="dp-summary-l">핵심 요약</div><div class="dp-summary-b">${summary}</div></div>
<div class="dp-openclose"><button class="op" onclick="dpOpenAll()">모두 열기</button><span class="dp-sep">|</span><button class="cl" onclick="dpCloseAll()">모두 닫기</button></div>
<div class="dp-acc" id="dpAcc-tech"><button class="dp-acc-h" onclick="dpToggle('tech')"><span>1. 기술적 분석</span><span class="dp-acc-chev">▾</span></button><div class="dp-acc-body"><div class="dp-placeholder"><strong>시세 데이터 연동 전</strong><br>OpenDART는 주가·거래량·이동평균선을 제공하지 않습니다.<br>향후 시세 API를 연결하면 예시와 같은 캔들차트와 기술적 지표를 표시할 수 있습니다.</div></div></div>
<div class="dp-acc open" id="dpAcc-fund"><button class="dp-acc-h" onclick="dpToggle('fund')"><span>2. 기본적 분석 — 공시 원문</span><span class="dp-acc-chev">▾</span></button><div class="dp-acc-body"><div class="dp-g2"><div><div class="dp-secl">손익 주요 계정 · ${report}</div>${row('매출·영업수익',rev)}${row('영업이익',op)}${row('당기순이익',net)}${row('기본주당이익',eps)}</div><div><div class="dp-secl">재무상태 주요 계정 · ${fs}</div>${row('자산총계',assets)}${row('부채총계',liab)}${row('자본총계',equity)}${row('현금 관련 계정',cash)}</div></div><div class="dp-insight"><div class="dp-insight-t">공시 데이터 기준</div><div class="dp-insight-b">DART 고유번호 ${esc(f.company?.corpCode)} · ${fs}재무제표(${esc(f.fsDivision)}) · ${esc(f.company?.corpName)} · 결산월 ${esc(f.company?.accMonth||'—')}</div></div><div style="margin-top:18px"><div class="dp-secl">재무상태표 전체 계정</div>${fullTable(rows.filter(r=>r.statement==='BS'))}</div><div style="margin-top:18px"><div class="dp-secl">손익계산서 전체 계정</div>${fullTable(rows.filter(r=>['IS','CIS'].includes(r.statement)))}</div></div></div>
<div class="dp-acc" id="dpAcc-valuation"><button class="dp-acc-h" onclick="dpToggle('valuation')"><span>3. 투자지표 및 재무비율</span><span class="dp-acc-chev">▾</span></button><div class="dp-acc-body"><div class="dp-share4"><div class="dp-share"><div class="dp-share-l">부채 비중</div><div class="dp-share-v">${Number.isFinite(debt)?debt.toFixed(1)+'%':'—'}</div><div class="dp-share-s">부채 ÷ 자산</div></div><div class="dp-share"><div class="dp-share-l">자기자본 비중</div><div class="dp-share-v">${Number.isFinite(equityRatio)?equityRatio.toFixed(1)+'%':'—'}</div><div class="dp-share-s">자본 ÷ 자산</div></div><div class="dp-share"><div class="dp-share-l">영업이익률</div><div class="dp-share-v">${Number.isFinite(opMargin)?opMargin.toFixed(1)+'%':'—'}</div><div class="dp-share-s">영업이익 ÷ 수익</div></div><div class="dp-share"><div class="dp-share-l">순이익률</div><div class="dp-share-v">${Number.isFinite(netMargin)?netMargin.toFixed(1)+'%':'—'}</div><div class="dp-share-s">순이익 ÷ 수익</div></div></div>${gauge('자기자본 비중',Number.isFinite(equityRatio)?equityRatio.toFixed(1)+'%':'—','자산 중 자본이 차지하는 비중입니다.',equityRatio||3)}${gauge('영업이익률',Number.isFinite(opMargin)?opMargin.toFixed(1)+'%':'—','업종별 수익 계정 차이 때문에 동일 업종 내 비교가 적절합니다.',Math.abs(opMargin||0)*3)}<div class="dp-placeholder">PER·PBR·배당수익률은 현재 주가와 발행주식수 데이터가 필요하므로 표시하지 않습니다.</div></div></div>
<div class="dp-acc" id="dpAcc-timeline"><button class="dp-acc-h" onclick="dpToggle('timeline')"><span>4. 공시 시계열</span><span class="dp-acc-chev">▾</span></button><div class="dp-acc-body"><div class="dp-tl"><div class="dp-tl-item"><div class="dp-tl-dot"></div><div class="dp-tl-date">${f.businessYear}년 · ${esc(f.reportName)}</div><div class="dp-tl-title">${esc(stock.name)} 정기보고서 재무제표 반영</div><div class="dp-tl-body">OpenDART ${fs}재무제표의 ${rows.length.toLocaleString('ko-KR')}개 계정을 수집해 페이지에 반영했습니다.</div></div><div class="dp-tl-item"><div class="dp-tl-dot"></div><div class="dp-tl-date">${esc(data.generatedAt?.slice(0,10)||'—')}</div><div class="dp-tl-title">SS Family 데이터 갱신</div><div class="dp-tl-body">기업개황과 재무제표를 API에서 다시 받아 정적 JSON으로 생성했습니다.</div></div></div></div></div>
<div class="dp-acc" id="dpAcc-thesis"><button class="dp-acc-h" onclick="dpToggle('thesis')"><span>5. 재무 체크포인트</span><span class="dp-acc-chev">▾</span></button><div class="dp-acc-body"><div class="dp-thesis"><div><div class="dp-thesis-t bull">확인 가능한 항목</div><div class="dp-thesis-item bull"><span class="dot">●</span><span>자산 대비 자기자본 비중 ${Number.isFinite(equityRatio)?equityRatio.toFixed(1)+'%':'계산 불가'}</span></div><div class="dp-thesis-item bull"><span class="dot">●</span><span>영업이익 전기 대비 ${pct(change(op))}</span></div><div class="dp-thesis-item bull"><span class="dot">●</span><span>당기순이익 전기 대비 ${pct(change(net))}</span></div></div><div><div class="dp-thesis-t bear">추가 확인 필요</div><div class="dp-thesis-item bear"><span class="dot">●</span><span>주가 기반 밸류에이션과 52주 가격 위치</span></div><div class="dp-thesis-item bear"><span class="dot">●</span><span>최근 분기 실적과 연간 실적의 지속 가능성</span></div><div class="dp-thesis-item bear"><span class="dot">●</span><span>사업보고서 주석과 현금흐름 세부 내역</span></div></div></div></div></div>
<div class="dp-acc" id="dpAcc-consensus"><button class="dp-acc-h" onclick="dpToggle('consensus')"><span>6. 애널리스트 컨센서스</span><span class="dp-acc-chev">▾</span></button><div class="dp-acc-body">${renderConsensus(data.consensus?.[code])}</div></div>`}
async function init(){const [stocks,data,consensus]=await Promise.all([fetch('data/stocks.json').then(r=>r.json()),fetch('data/financials.json').then(r=>r.json()),fetch('data/consensus.json').then(r=>r.json())]);const stock=stocks.find(s=>s.code===code);if(!stock)throw new Error('등록되지 않은 종목입니다.');const f=data.stocks?.[code];data.consensus=consensus.stocks||{};document.title=`${stock.name} | SS Family`;if(!f)throw new Error('이 종목의 DART 데이터가 없습니다. update_dart.ps1을 실행해 주세요.');render(stock,f,data)}
init().catch(e=>{document.getElementById('detailRoot').innerHTML=`<div class="dp-placeholder">${esc(e.message)}</div>`});
